import { Product } from '../types';

export const INITIAL_PRODUCTS: Product[] = [
  // 1. GROCERY (5 items)
  {
    id: 'prod-groc-01',
    name: 'Daawat Rozana Super Basmati Rice (5 kg)',
    category: 'grocery',
    subCategory: 'Rice',
    brand: 'Daawat',
    description: 'Long grain aromatic aged basmati rice perfect for daily cooking, biryani, and pulao. Carefully processed and aged to deliver fluffy, non-sticky grains every time.',
    specifications: {
      'Net Weight': '5 kg',
      'Grain Length': 'Aged Long Grain',
      'Diet Type': 'Vegetarian',
      'Shelf Life': '24 Months',
      'Country of Origin': 'India',
    },
    costPrice: 290,
    sellingPrice: 385,
    originalPrice: 475,
    discountPercentage: 19,
    stockQuantity: 45,
    sku: 'MM-GRC-RIC-001',
    status: 'in_stock',
    isFeatured: true,
    isBestSeller: true,
    rating: 4.6,
    reviewCount: 320,
    images: [
      'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?w=800&auto=format&fit=crop&q=80'
    ],
    tags: ['basmati', 'rice', 'grocery', 'daawat', 'daily']
  },
  {
    id: 'prod-groc-02',
    name: 'Tata Sampann Unpolished Toor Dal (1 kg)',
    category: 'grocery',
    subCategory: 'Dal',
    brand: 'Tata Sampann',
    description: '100% unpolished toor dal rich in natural protein and essential dietary fiber. Free from artificial polish such as water, oil, or leather polish, ensuring natural goodness.',
    specifications: {
      'Net Quantity': '1 kg',
      'Diet Type': 'Vegetarian',
      'Nutrient Feature': 'Rich in Natural Dietary Protein',
      'Processing': 'Unpolished',
      'Country of Origin': 'India',
    },
    costPrice: 125,
    sellingPrice: 168,
    originalPrice: 195,
    discountPercentage: 14,
    stockQuantity: 60,
    sku: 'MM-GRC-DAL-002',
    status: 'in_stock',
    isFeatured: false,
    isBestSeller: true,
    rating: 4.7,
    reviewCount: 185,
    images: [
      'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&auto=format&fit=crop&q=80'
    ],
    tags: ['dal', 'pulses', 'tata', 'protein', 'grocery']
  },
  {
    id: 'prod-groc-03',
    name: 'Madhur Pure & Hygienic Sulphur-Free Sugar (1 kg)',
    category: 'grocery',
    subCategory: 'Sugar',
    brand: 'Madhur',
    description: 'Refined under 100% untouched automated European technology. Clean, sparkling white crystals free from sulphur impurities for sweetening tea, coffee, and traditional sweets.',
    specifications: {
      'Net Weight': '1 kg',
      'Type': 'Sulphur-free Crystal Sugar',
      'Package Type': 'Hygienic Sealed Pouch',
      'Brand': 'Madhur',
    },
    costPrice: 42,
    sellingPrice: 56,
    originalPrice: 65,
    discountPercentage: 14,
    stockQuantity: 80,
    sku: 'MM-GRC-SUG-003',
    status: 'in_stock',
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: true,
    rating: 4.5,
    reviewCount: 92,
    images: [
      'https://images.unsplash.com/photo-1622484216802-99079a4ea9bd?w=800&auto=format&fit=crop&q=80'
    ],
    tags: ['sugar', 'sweetener', 'madhur', 'grocery', 'baking']
  },
  {
    id: 'prod-groc-04',
    name: 'Fortune Sunlite Refined Sunflower Oil (1 L Pouch)',
    category: 'grocery',
    subCategory: 'Cooking essentials',
    brand: 'Fortune',
    description: 'Light and healthy refined sunflower cooking oil enriched with Vitamins A & D. Low absorption technology ensures light and crispy food that keeps your heart active.',
    specifications: {
      'Volume': '1 Litre',
      'Form': 'Liquid Pouch',
      'Enriched With': 'Vitamins A and D',
      'Ideal For': 'Deep frying, sautéing and Indian curries',
    },
    costPrice: 110,
    sellingPrice: 142,
    originalPrice: 170,
    discountPercentage: 16,
    stockQuantity: 50,
    sku: 'MM-GRC-OIL-004',
    status: 'in_stock',
    isFeatured: true,
    isBestSeller: true,
    rating: 4.8,
    reviewCount: 410,
    images: [
      'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800&auto=format&fit=crop&q=80'
    ],
    tags: ['sunflower oil', 'cooking oil', 'fortune', 'grocery', 'oil']
  },
  {
    id: 'prod-groc-05',
    name: 'Brooke Bond Red Label Strong Tea Blend (500 g)',
    category: 'grocery',
    subCategory: 'Beverages',
    brand: 'Red Label',
    description: 'Crafted with the finest chosen Assam and Dooars tea leaves. Delivers an enticing aroma, rich red colour, and irresistible warmth to bring families together over chai.',
    specifications: {
      'Net Weight': '500 g',
      'Flavour': 'Rich & Strong Kadak Chai',
      'Packaging': 'Aroma-sealed Carton',
      'Shelf Life': '12 Months',
    },
    costPrice: 180,
    sellingPrice: 245,
    originalPrice: 290,
    discountPercentage: 15,
    stockQuantity: 35,
    sku: 'MM-GRC-TEA-005',
    status: 'in_stock',
    isFeatured: false,
    isBestSeller: true,
    rating: 4.7,
    reviewCount: 260,
    images: [
      'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=800&auto=format&fit=crop&q=80'
    ],
    tags: ['tea', 'chai', 'red label', 'beverages', 'grocery']
  },

  // 2. ELECTRONICS (5 items)
  {
    id: 'prod-elec-01',
    name: 'boAt Deuce 65W Fast Charging Type-C Braided Cable (1.5m)',
    category: 'electronics',
    subCategory: 'Charging cables',
    brand: 'boAt',
    description: 'Rugged nylon braided ultra-durable fast charging cable with 65W Power Delivery support and 480 Mbps high speed data sync. Compatible with smartphones, tablets, and Type-C laptops.',
    specifications: {
      'Cable Length': '1.5 Metres',
      'Power Output': 'Up to 65 Watts',
      'Connector Type': 'USB Type-A to Type-C',
      'Material': 'Tangle-free Nylon Braided',
      'Warranty': '1 Year boAt Warranty',
    },
    costPrice: 140,
    sellingPrice: 299,
    originalPrice: 699,
    discountPercentage: 57,
    stockQuantity: 40,
    sku: 'MM-ELC-CBL-001',
    status: 'in_stock',
    isFeatured: true,
    isBestSeller: true,
    rating: 4.5,
    reviewCount: 512,
    images: [
      'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1598256989800-fe5f95da9787?w=800&auto=format&fit=crop&q=80'
    ],
    tags: ['type-c', 'charging cable', 'boat', 'fast charging', 'electronics']
  },
  {
    id: 'prod-elec-02',
    name: 'Portronics Adapto 20W PD Dual Port Fast Wall Charger',
    category: 'electronics',
    subCategory: 'Chargers',
    brand: 'Portronics',
    description: 'Compact 20 Watt dual port wall adapter featuring USB-C Power Delivery and QC 3.0 USB-A port. Smart IC protection safeguards against over-voltage, overheating and short circuits.',
    specifications: {
      'Wattage': '20 Watts PD + QC',
      'Ports': '1x USB-C + 1x USB-A',
      'Input': 'AC 100-240V 50/60Hz',
      'Features': 'Smart Temperature Protection',
      'Color': 'Classic White',
    },
    costPrice: 260,
    sellingPrice: 489,
    originalPrice: 999,
    discountPercentage: 51,
    stockQuantity: 28,
    sku: 'MM-ELC-CHG-002',
    status: 'in_stock',
    isFeatured: true,
    isBestSeller: false,
    rating: 4.4,
    reviewCount: 140,
    images: [
      'https://images.unsplash.com/photo-1585338107529-13afc5f02586?w=800&auto=format&fit=crop&q=80'
    ],
    tags: ['charger', 'adapter', 'portronics', 'fast charger', 'mobile accessories']
  },
  {
    id: 'prod-elec-03',
    name: 'Boult Audio BassBuds In-Ear Wired Earphones with HD Mic',
    category: 'electronics',
    subCategory: 'Earphones',
    brand: 'Boult Audio',
    description: 'Engineered with custom 10mm neodymium acoustic drivers delivering deep punchy bass, pristine vocals, and in-line button for calls and music controls.',
    specifications: {
      'Jack Type': '3.5 mm Gold Plated Angled Jack',
      'Driver Size': '10 mm High Fidelity',
      'Microphone': 'Built-in Noise-Isolating HD Mic',
      'Cable Length': '1.2 Metres',
    },
    costPrice: 170,
    sellingPrice: 349,
    originalPrice: 899,
    discountPercentage: 61,
    stockQuantity: 34,
    sku: 'MM-ELC-EAR-003',
    status: 'in_stock',
    isFeatured: false,
    isBestSeller: true,
    rating: 4.3,
    reviewCount: 380,
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80'
    ],
    tags: ['earphones', 'boult', 'audio', 'headphones', 'bass']
  },
  {
    id: 'prod-elec-04',
    name: 'Aluminium Ergonomic Foldable Desktop Phone & Tablet Stand',
    category: 'electronics',
    subCategory: 'Phone stands',
    brand: 'Madina Essentials',
    description: 'Heavy-duty CNC machined aluminium alloy stand with 270° dual-axis angle adjustment. Non-slip silicone padding protects your device while keeping hands free for video calls.',
    specifications: {
      'Material': 'Premium Matte Aluminium Alloy',
      'Compatibility': 'Smartphones & Tablets (4 to 11 inches)',
      'Adjustability': 'Dual Axis 270 Degree Rotation',
      'Anti-slip': 'Silicone Cushioned Base & Hooks',
    },
    costPrice: 95,
    sellingPrice: 229,
    originalPrice: 499,
    discountPercentage: 54,
    stockQuantity: 55,
    sku: 'MM-ELC-STN-004',
    status: 'in_stock',
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: true,
    rating: 4.6,
    reviewCount: 98,
    images: [
      'https://images.unsplash.com/photo-1586105251261-72a756497a11?w=800&auto=format&fit=crop&q=80'
    ],
    tags: ['phone stand', 'holder', 'desk accessory', 'mobile stand']
  },
  {
    id: 'prod-elec-05',
    name: 'Ambrane 10000mAh Compact Slim Power Bank (22.5W Fast Charge)',
    category: 'electronics',
    subCategory: 'Mobile accessories',
    brand: 'Ambrane',
    description: 'Pocket-sized lightweight 10000mAh high-density lithium-polymer battery bank with triple output ports (Dual USB + Type-C PD) for lightning fast recharges on the go.',
    specifications: {
      'Battery Capacity': '10,000 mAh Li-Polymer',
      'Max Output': '22.5W Quick Charge 3.0 & PD',
      'Number of Ports': '2 USB-A + 1 USB-C Dual Direction',
      'Weight': '185 grams (Ultra-pocket friendly)',
    },
    costPrice: 520,
    sellingPrice: 899,
    originalPrice: 1599,
    discountPercentage: 44,
    stockQuantity: 18,
    sku: 'MM-ELC-PWR-005',
    status: 'low_stock',
    isFeatured: true,
    isBestSeller: true,
    rating: 4.6,
    reviewCount: 215,
    images: [
      'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=800&auto=format&fit=crop&q=80'
    ],
    tags: ['power bank', 'ambrane', 'battery', 'fast charge', 'electronics']
  },

  // 3. FASHION (5 items)
  {
    id: 'prod-fash-01',
    name: "Classic Men's 100% Combed Cotton Pique Polo T-Shirt (Navy Blue)",
    category: 'fashion',
    subCategory: 'T-Shirts',
    brand: 'Urban Thread',
    description: 'Breathable 220 GSM bio-washed pre-shrunk cotton polo. Tailored collar, reinforced two-button placket, and side slits ensure effortless comfort throughout the Indian summer.',
    specifications: {
      'Fabric': '100% Super-Combed Cotton Pique',
      'Fit': 'Regular Comfort Fit',
      'Collar': 'Ribbed Rib Polo Collar',
      'Care': 'Machine wash cold, tumble dry low',
      'Sizes Available': 'M, L, XL, XXL',
    },
    costPrice: 220,
    sellingPrice: 449,
    originalPrice: 899,
    discountPercentage: 50,
    stockQuantity: 30,
    sku: 'MM-FSH-POL-001',
    status: 'in_stock',
    isFeatured: true,
    isBestSeller: true,
    rating: 4.4,
    reviewCount: 160,
    images: [
      'https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop&q=80'
    ],
    tags: ['polo', 'tshirt', 'men', 'cotton', 'fashion']
  },
  {
    id: 'prod-fash-02',
    name: "Men's Premium Breathable Linen Casual Mandarin Collar Shirt (Crisp White)",
    category: 'fashion',
    subCategory: 'Shirts',
    brand: 'Al-Madina Heritage',
    description: 'Crafted from pure blended linen for a featherlight cooling experience. Features clean roll-up sleeve tabs, curved hemline, and an elegant Nehru mandarin collar.',
    specifications: {
      'Fabric': 'Cotton Linen Blend',
      'Pattern': 'Solid Crisp White',
      'Collar Style': 'Mandarin Nehru Collar',
      'Sleeve Length': 'Full Sleeves with Roll-up Tab',
    },
    costPrice: 380,
    sellingPrice: 699,
    originalPrice: 1399,
    discountPercentage: 50,
    stockQuantity: 24,
    sku: 'MM-FSH-SHT-002',
    status: 'in_stock',
    isFeatured: true,
    isBestSeller: false,
    isNewArrival: true,
    rating: 4.7,
    reviewCount: 88,
    images: [
      'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&auto=format&fit=crop&q=80'
    ],
    tags: ['shirt', 'linen', 'men fashion', 'white shirt', 'kurta style']
  },
  {
    id: 'prod-fash-03',
    name: 'Eco-Friendly Heavy Duty Canvas Multi-Compartment Everyday Tote Bag',
    category: 'fashion',
    subCategory: 'Bags',
    brand: 'EcoVibe India',
    description: 'Sustainable 16oz natural canvas tote with zipper closure and padded shoulder straps. Roomy enough to hold groceries, a 14-inch laptop, water bottle, and daily essentials.',
    specifications: {
      'Material': '100% Organic Heavy Cotton Canvas',
      'Closure': 'Smooth Top Zipper Closure',
      'Dimensions': '38cm x 34cm x 12cm',
      'Pockets': '1 Inner Zip Pocket + 2 Quick Slip Pouches',
    },
    costPrice: 160,
    sellingPrice: 329,
    originalPrice: 699,
    discountPercentage: 53,
    stockQuantity: 42,
    sku: 'MM-FSH-BAG-003',
    status: 'in_stock',
    isFeatured: false,
    isBestSeller: true,
    rating: 4.5,
    reviewCount: 110,
    images: [
      'https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&auto=format&fit=crop&q=80'
    ],
    tags: ['tote bag', 'canvas bag', 'handbag', 'fashion', 'sustainable']
  },
  {
    id: 'prod-fash-04',
    name: "Timex Classic Minimalist Analog Quartz Watch with Brown Leather Strap",
    category: 'fashion',
    subCategory: 'Watches',
    brand: 'Timex',
    description: 'Refined slim profile watch featuring a clean sunray dial, gold-toned bezel, scratch-resistant mineral crystal glass, and genuine stitched brown calfskin leather band.',
    specifications: {
      'Movement': 'Japanese Quartz Precision',
      'Dial Diameter': '40 mm',
      'Water Resistance': '30 Metres (Splash Proof)',
      'Strap Material': 'Genuine Stitched Leather',
    },
    costPrice: 680,
    sellingPrice: 1199,
    originalPrice: 2199,
    discountPercentage: 45,
    stockQuantity: 15,
    sku: 'MM-FSH-WTC-004',
    status: 'low_stock',
    isFeatured: true,
    isBestSeller: false,
    rating: 4.8,
    reviewCount: 195,
    images: [
      'https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=800&auto=format&fit=crop&q=80'
    ],
    tags: ['watch', 'timex', 'analog', 'leather watch', 'men fashion']
  },
  {
    id: 'prod-fash-05',
    name: 'Traditional Gold-Plated Kundan Floral Choker Necklace & Earring Set',
    category: 'fashion',
    subCategory: 'Fashion jewellery',
    brand: 'Noor Ethnic',
    description: 'Stunning handcrafted ethnic kundan jewelry set adorned with teardrop faux pearls and shimmering Austrian stones. Perfect for weddings, Eid, festivals, and parties.',
    specifications: {
      'Plating': '22K Micro Gold Micron Plating',
      'Stone Type': 'Handset Kundan & Shell Pearls',
      'Includes': '1 Adjustable Choker + 1 Pair Matching Jhumka Earrings',
      'Skin Friendly': 'Lead & Nickel Free Non-Allergenic',
    },
    costPrice: 240,
    sellingPrice: 499,
    originalPrice: 1299,
    discountPercentage: 62,
    stockQuantity: 25,
    sku: 'MM-FSH-JWL-005',
    status: 'in_stock',
    isFeatured: false,
    isBestSeller: true,
    rating: 4.6,
    reviewCount: 135,
    images: [
      'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&auto=format&fit=crop&q=80'
    ],
    tags: ['jewellery', 'necklace', 'earrings', 'traditional', 'wedding', 'kundan']
  },

  // 4. OILS & PERSONAL CARE (5 items)
  {
    id: 'prod-oil-01',
    name: 'Parachute 100% Pure Coconut Hair Oil (500 ml Bottle)',
    category: 'oils-personal-care',
    subCategory: 'Hair oils',
    brand: 'Parachute',
    description: 'Made from naturally sun-dried Malabar coconuts through a stringent 5-stage purification process. Deeply nourishes hair roots from within, preventing dryness and split ends.',
    specifications: {
      'Volume': '500 ml',
      'Purity': '100% Pure Coconut Oil',
      'Preservatives': 'No Added Preservatives or Chemicals',
      'Suitable For': 'All Hair and Scalp Types',
    },
    costPrice: 145,
    sellingPrice: 189,
    originalPrice: 225,
    discountPercentage: 16,
    stockQuantity: 50,
    sku: 'MM-OIL-PRC-001',
    status: 'in_stock',
    isFeatured: true,
    isBestSeller: true,
    rating: 4.8,
    reviewCount: 620,
    images: [
      'https://images.unsplash.com/photo-1608248597359-251f084f7278?w=800&auto=format&fit=crop&q=80'
    ],
    tags: ['coconut oil', 'hair oil', 'parachute', 'scalp care', 'personal care']
  },
  {
    id: 'prod-oil-02',
    name: 'Nivea Nourishing Cocoa Butter Body Milk Deep Moisture Lotion (400 ml)',
    category: 'oils-personal-care',
    subCategory: 'Body-care products',
    brand: 'Nivea',
    description: 'Enriched with natural Cocoa Butter and Hydra IQ deep moisture serum. Delivers 48 hours of intense hydration to heal dry and rough skin with a soothing warm fragrance.',
    specifications: {
      'Volume': '400 ml',
      'Skin Type': 'Very Dry Skin',
      'Key Ingredients': 'Cocoa Butter & Vitamin E',
      'Duration': '48 Hour Moisture Lock',
    },
    costPrice: 230,
    sellingPrice: 325,
    originalPrice: 425,
    discountPercentage: 24,
    stockQuantity: 32,
    sku: 'MM-OIL-NIV-002',
    status: 'in_stock',
    isFeatured: false,
    isBestSeller: true,
    rating: 4.7,
    reviewCount: 310,
    images: [
      'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&auto=format&fit=crop&q=80'
    ],
    tags: ['lotion', 'nivea', 'body milk', 'cocoa butter', 'personal care']
  },
  {
    id: 'prod-oil-03',
    name: 'Dettol Original Germ Protection Liquid Handwash Refill (750 ml Pouch)',
    category: 'oils-personal-care',
    subCategory: 'Personal-care products',
    brand: 'Dettol',
    description: 'Provides 100% better protection against illness-causing germs. Formulated with pine fragrance and pH-balanced glycerin to leave hands hygienically clean and soft.',
    specifications: {
      'Net Volume': '750 ml Value Refill',
      'Form': 'Antibacterial Liquid',
      'Protection': 'Kills 99.9% of Germs',
      'pH Balanced': 'Yes, Dermatologically Tested',
    },
    costPrice: 85,
    sellingPrice: 119,
    originalPrice: 145,
    discountPercentage: 18,
    stockQuantity: 65,
    sku: 'MM-OIL-DTL-003',
    status: 'in_stock',
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: true,
    rating: 4.6,
    reviewCount: 190,
    images: [
      'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&auto=format&fit=crop&q=80'
    ],
    tags: ['handwash', 'dettol', 'hygiene', 'germ protection', 'personal care']
  },
  {
    id: 'prod-oil-04',
    name: 'Bombay Shaving Company Precision Cordless Beard & Hair Trimmer',
    category: 'oils-personal-care',
    subCategory: 'Grooming accessories',
    brand: 'Bombay Shaving Co',
    description: 'Self-sharpening stainless steel T-blades with 20 length settings (0.5mm to 10mm). Features 80 minutes of cordless runtime on USB quick charging and IPX6 water resistance.',
    specifications: {
      'Blade Material': 'Self-Sharpening Stainless Steel',
      'Run Time': '80 Minutes Continuous Cordless Run',
      'Length Settings': '20 Precise Lock-in Settings (0.5 - 10mm)',
      'Charging Port': 'Universal Type-C Fast Charging',
    },
    costPrice: 480,
    sellingPrice: 799,
    originalPrice: 1499,
    discountPercentage: 47,
    stockQuantity: 20,
    sku: 'MM-OIL-TRM-004',
    status: 'in_stock',
    isFeatured: true,
    isBestSeller: false,
    rating: 4.5,
    reviewCount: 148,
    images: [
      'https://images.unsplash.com/photo-1621607512214-68297480165e?w=800&auto=format&fit=crop&q=80'
    ],
    tags: ['trimmer', 'grooming', 'beard', 'shaving', 'men grooming']
  },
  {
    id: 'prod-oil-05',
    name: 'Himalaya Herbals Purifying Neem Face Wash (200 ml)',
    category: 'oils-personal-care',
    subCategory: 'Daily personal-care items',
    brand: 'Himalaya',
    description: 'Soap-free herbal formulation that clears impurities and helps prevent pimples and acne. Blended with Neem known for antibacterial properties and Turmeric for soothing glow.',
    specifications: {
      'Net Volume': '200 ml',
      'Key Ingredients': 'Neem Leaf Extract & Wild Turmeric',
      'Form': 'Soap-Free Cleansing Gel',
      'Suitable For': 'Normal to Oily & Acne-Prone Skin',
    },
    costPrice: 140,
    sellingPrice: 195,
    originalPrice: 240,
    discountPercentage: 19,
    stockQuantity: 40,
    sku: 'MM-OIL-HML-005',
    status: 'in_stock',
    isFeatured: false,
    isBestSeller: true,
    rating: 4.7,
    reviewCount: 480,
    images: [
      'https://images.unsplash.com/photo-1556228722-d0b71c26b527?w=800&auto=format&fit=crop&q=80'
    ],
    tags: ['facewash', 'himalaya', 'neem', 'skincare', 'daily use']
  }
];

export const CATEGORY_DEFINITIONS = [
  {
    id: 'grocery',
    name: 'Grocery',
    tagline: 'Fresh staples, cooking essentials & daily snacks',
    icon: 'ShoppingBasket',
    color: 'emerald',
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&auto=format&fit=crop&q=80',
    subCategories: [
      'All',
      'Rice',
      'Dal',
      'Sugar',
      'Biscuits',
      'Snacks',
      'Beverages',
      'Cooking essentials',
      'Cleaning products',
      'Daily-use products'
    ]
  },
  {
    id: 'electronics',
    name: 'Electronics',
    tagline: 'Cables, chargers, audio & smart accessories',
    icon: 'Smartphone',
    color: 'blue',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80',
    subCategories: [
      'All',
      'Charging cables',
      'Chargers',
      'Earphones',
      'Phone stands',
      'Mobile accessories',
      'Small electronic accessories'
    ]
  },
  {
    id: 'fashion',
    name: 'Fashion',
    tagline: 'Clothing, shirts, bags, watches & jewellery',
    icon: 'Shirt',
    color: 'amber',
    image: 'https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=800&auto=format&fit=crop&q=80',
    subCategories: [
      'All',
      'T-Shirts',
      'Shirts',
      'Bags',
      'Watches',
      'Fashion accessories',
      'Fashion jewellery'
    ]
  },
  {
    id: 'oils-personal-care',
    name: 'Oils & Personal Care',
    tagline: 'Hair oils, lotions, grooming & daily hygiene',
    icon: 'Sparkles',
    color: 'teal',
    image: 'https://images.unsplash.com/photo-1608248597359-251f084f7278?w=800&auto=format&fit=crop&q=80',
    subCategories: [
      'All',
      'Hair oils',
      'Body-care products',
      'Personal-care products',
      'Grooming accessories',
      'Daily personal-care items'
    ]
  }
] as const;

export const DEFAULT_STORE_SETTINGS: import('../types').StoreSettings = {
  platformFee: 5,
  deliveryFee: 40,
  deliveryCharge: 40,
  freeDeliveryThreshold: 499,
  estimatedDeliveryTime: 'Within 2 to 4 hours (Local Express)',
  returnWindowDays: 7,
  supportPhone: '+91 98765 43210',
  supportWhatsApp: '+91 98765 43210',
  supportEmail: 'support@madinamart.com',
  contactPhone: '+91 98765 43210',
  contactWhatsapp: '+91 98765 43210',
  operatingCity: 'Local Delivery Zone',
  lowStockThreshold: 10,
  bannerTexts: [
    '⚡ Superfast Local Delivery across town in 2-4 hours!',
    '🎉 Special Offer: FREE Delivery on all orders above ₹499!',
    '🤝 Trusted Local Reselling Marketplace: 100% Genuine Products Guaranteed',
    '💵 Cash On Delivery (COD) Available on every single order'
  ]
};
